In [34]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [35]:
enc = OneHotEncoder(handle_unknown='ignore')
X = [['Male', 1], 
     ['Female', 3], 
     ['Female', 2]]
enc.fit(X)

OneHotEncoder(handle_unknown='ignore')

In [36]:
print(enc.transform(X))

  (0, 1)	1.0
  (0, 2)	1.0
  (1, 0)	1.0
  (1, 4)	1.0
  (2, 0)	1.0
  (2, 3)	1.0


In [37]:
enc.transform(X).toarray()

array([[0., 1., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0.]])

In [38]:
enc.categories_

[array(['Female', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]

In [39]:
enc.transform([['Female',1], ['Male',5]]).toarray()

array([[1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [40]:
enc.inverse_transform([[0, 1, 1, 0, 0], [0, 0, 0, 1, 0]])

array([['Male', 1],
       [None, 2]], dtype=object)

In [41]:
enc.get_feature_names_out(['gender', 'group'])

array(['gender_Female', 'gender_Male', 'group_1', 'group_2', 'group_3'],
      dtype=object)

In [42]:
drop_enc = OneHotEncoder(drop='first').fit(X)

In [43]:
drop_enc.categories_

[array(['Female', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]

In [44]:
drop_enc.transform([['Female', 1], ['Male',3]]).toarray()

array([[0., 0., 0.],
       [1., 0., 1.]])

In [45]:
drop_binary_enc = OneHotEncoder(drop='if_binary',handle_unknown='ignore').fit(X)
drop_binary_enc.transform([['Female', 1], ['Male', 4]]).toarray()

D:\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:170: UserWarning: Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(


array([[0., 1., 0., 0.],
       [1., 0., 0., 0.]])

In [46]:
# import numpy as np
# X = np.array([["a"] * 5 + ["b"] * 20 + ["c"] * 10 + ["d"] * 3], dtype=object).T
# ohe = OneHotEncoder(max_categories=3, sparse=False).fit(X)
# ohe.infrequent_categories_

In [47]:
# ohe.transform([["a"], ["b"]])

# 如果类别数据是字符串类型的，可以使用pandas的API进行哑编码转换

In [48]:
import pandas as pd

a = pd.DataFrame([
    ['a', 1, 2],
    ['b', 1, 1],
    ['a', 2, 1],
    ['c', 1, 2],
    ['c', 1, 2]
], columns=['c1', 'c2', 'c3'])
a = pd.get_dummies(a)
a

c2  c3  c1_a  c1_b  c1_c
0   1   2     1     0     0
1   1   1     0     1     0
2   2   1     1     0     0
3   1   2     0     0     1
4   1   2     0     0     1