In [1]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

In [2]:
X=np.array([[2,3,4]])

In [3]:
poly = PolynomialFeatures(degree=2, interaction_only=True, include_bias=False)
X_poly = poly.fit_transform(X)
print(X_poly)

[[ 2.  3.  4.  6.  8. 12.]]


In [4]:
poly = PolynomialFeatures(degree=2, interaction_only=False, include_bias=False)
X_poly = poly.fit_transform(X)
print(X_poly)

[[ 2.  3.  4.  4.  6.  8.  9. 12. 16.]]


In [5]:
poly = PolynomialFeatures(degree=2, interaction_only=False, include_bias=True)
X_poly = poly.fit_transform(X)
print(X_poly)

[[ 1.  2.  3.  4.  4.  6.  8.  9. 12. 16.]]


In [6]:
poly = PolynomialFeatures(degree=3, interaction_only=True, include_bias=False)
X_poly = poly.fit_transform(X)
print(X_poly)

[[ 2.  3.  4.  6.  8. 12. 24.]]


In [7]:
poly = PolynomialFeatures(degree=3, interaction_only=False, include_bias=False)
X_poly = poly.fit_transform(X)
print(X_poly)

[[ 2.  3.  4.  4.  6.  8.  9. 12. 16.  8. 12. 16. 18. 24. 32. 27. 36. 48.
  64.]]
